### ISSUE TITLE
Attendance Tracker (Stretch)

### ISSUE THREAD

**Issue by loetek** [loetek/Show-of-Hands---JS-React---FrontEnd-Capstone#15]
Setup attendance tracker so that it will register a users attendance based on days they attended and times they clocked in.

- [ ] Create a new database that will hold the values needed.
- [ ] Create input field/trigger to log event.
- [ ] Connect trigger to logic that will add the new db object.
- [ ] Read and display events in landingpage.
- [ ] This needs to only display per user  for the student.
- [ ] It also needs to display for student and cohort to the instructor.
- [ ] Display results in chart.js
